language: node_js
os: osx
osx_image: xcode10.2
node_js:
  - "12"

install:
  - npm install

script:
  - npm run dist

deploy:
  provider: releases
  skip_cleanup: true
  file: "release/*.zip"
  file_glob: true
  api_key: "$GH_TOKEN"
  on:
    tags: true
    branch: master
