language: node_js
os: osx
osx_image: xcode10.2
sudo: required
node_js:
  - "12"

before_install:
  - stty cols 80

install:
  - npm ci

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      script: npm run pack-pro
    - stage: test
      script: npm run pack-pro && npm run unit
    - stage: deploy
      script: npm run dist

deploy:
  provider: releases
  skip_cleanup: true
  file: "release/*.zip"
  file_glob: true
  api_key: "$GH_TOKEN"
  on:
    tags: true
    branch: master
