language: node_js
sudo: required
node_js:
  - "12"

install:
  - npm ci

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
      os: linux
      dist: trusty
      script: npm run pack-pro
    - stage: test
      os: linux
      dist: trusty
      before_install:
        - stty cols 80
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
        - fluxbox >/dev/null 2>&1 &
      script: npm run pack-pro && npm run unit
    - stage: deploy
      os: osx
      osx_image: xcode10.2
      script: npm run dist

deploy:
  provider: releases
  skip_cleanup: true
  file: "release/*.zip"
  file_glob: true
  api_key: "$GH_TOKEN"
  on:
    tags: true
    branch: master
